# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 703)
        font = QtGui.QFont()
        font.setPointSize(18)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_unlock = QtWidgets.QPushButton(self.centralwidget)
        self.btn_unlock.setObjectName("btn_unlock")
        self.horizontalLayout.addWidget(self.btn_unlock)
        self.btn_lock = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lock.setObjectName("btn_lock")
        self.horizontalLayout.addWidget(self.btn_lock)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_ClearCurrentCount = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_ClearCurrentCount.setFont(font)
        self.btn_ClearCurrentCount.setObjectName("btn_ClearCurrentCount")
        self.verticalLayout.addWidget(self.btn_ClearCurrentCount)
        self.gridLayout_SettingAlarmValue = QtWidgets.QGridLayout()
        self.gridLayout_SettingAlarmValue.setObjectName("gridLayout_SettingAlarmValue")
        self.btn_SaveAlarmValue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SaveAlarmValue.setObjectName("btn_SaveAlarmValue")
        self.gridLayout_SettingAlarmValue.addWidget(self.btn_SaveAlarmValue, 5, 3, 1, 1)
        self.lbl_Sensor_1SV_Lower = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_1SV_Lower.setObjectName("lbl_Sensor_1SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_1SV_Lower, 1, 1, 1, 1)
        self.txt_Sensor_4SV_Upper = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_4SV_Upper.setObjectName("txt_Sensor_4SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_4SV_Upper, 4, 5, 1, 1)
        self.lbl_Sensor_3SV_Lower = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_3SV_Lower.setObjectName("lbl_Sensor_3SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_3SV_Lower, 3, 1, 1, 1)
        self.lbl_Sensor_2SV = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_2SV.setObjectName("lbl_Sensor_2SV")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_2SV, 2, 0, 1, 1)
        self.lbl_Sensor_3SV = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_3SV.setObjectName("lbl_Sensor_3SV")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_3SV, 3, 0, 1, 1)
        self.txt_Sensor_1SV_Lower = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_1SV_Lower.setObjectName("txt_Sensor_1SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_1SV_Lower, 1, 3, 1, 1)
        self.lbl_Sensor_4SV = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_4SV.setObjectName("lbl_Sensor_4SV")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_4SV, 4, 0, 1, 1)
        self.txt_Sensor_4SV_Lower = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_4SV_Lower.setObjectName("txt_Sensor_4SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_4SV_Lower, 4, 3, 1, 1)
        self.lbl_Sensor_1SV_Upper = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_1SV_Upper.setObjectName("lbl_Sensor_1SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_1SV_Upper, 1, 4, 1, 1)
        self.lbl_Sensor_3SV_Upper = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_3SV_Upper.setObjectName("lbl_Sensor_3SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_3SV_Upper, 3, 4, 1, 1)
        self.lbl_Sensor_1SV = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_1SV.setObjectName("lbl_Sensor_1SV")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_1SV, 1, 0, 1, 1)
        self.txt_Sensor_2SV_Lower = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_2SV_Lower.setObjectName("txt_Sensor_2SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_2SV_Lower, 2, 3, 1, 1)
        self.lbl_Sensor_4SV_Lower = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_4SV_Lower.setObjectName("lbl_Sensor_4SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_4SV_Lower, 4, 1, 1, 1)
        self.lbl_Sensor_2SV_Upper = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_2SV_Upper.setObjectName("lbl_Sensor_2SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_2SV_Upper, 2, 4, 1, 1)
        self.lbl_Sensor_4SV_Upper = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_4SV_Upper.setObjectName("lbl_Sensor_4SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_4SV_Upper, 4, 4, 1, 1)
        self.txt_Sensor_2SV_Upper = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_2SV_Upper.setObjectName("txt_Sensor_2SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_2SV_Upper, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_SettingAlarmValue.addWidget(self.label, 0, 3, 1, 1)
        self.txt_Sensor_3SV_Lower = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_3SV_Lower.setObjectName("txt_Sensor_3SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_3SV_Lower, 3, 3, 1, 1)
        self.txt_Sensor_1SV_Upper = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_1SV_Upper.setObjectName("txt_Sensor_1SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_1SV_Upper, 1, 5, 1, 1)
        self.txt_Sensor_3SV_Upper = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Sensor_3SV_Upper.setObjectName("txt_Sensor_3SV_Upper")
        self.gridLayout_SettingAlarmValue.addWidget(self.txt_Sensor_3SV_Upper, 3, 5, 1, 1)
        self.lbl_Sensor_2SV_Lower = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sensor_2SV_Lower.setObjectName("lbl_Sensor_2SV_Lower")
        self.gridLayout_SettingAlarmValue.addWidget(self.lbl_Sensor_2SV_Lower, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_SettingAlarmValue)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lbl_CalibrationCoefficient = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CalibrationCoefficient.setObjectName("lbl_CalibrationCoefficient")
        self.gridLayout_6.addWidget(self.lbl_CalibrationCoefficient, 4, 0, 1, 1)
        self.btn_SaveCalibrationCoefficient = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SaveCalibrationCoefficient.setObjectName("btn_SaveCalibrationCoefficient")
        self.gridLayout_6.addWidget(self.btn_SaveCalibrationCoefficient, 5, 2, 1, 1)
        self.txt_CurrentPressure = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_CurrentPressure.setObjectName("txt_CurrentPressure")
        self.gridLayout_6.addWidget(self.txt_CurrentPressure, 1, 2, 1, 1)
        self.lbl_CurrentPressure = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CurrentPressure.setObjectName("lbl_CurrentPressure")
        self.gridLayout_6.addWidget(self.lbl_CurrentPressure, 1, 0, 1, 1)
        self.txt_CalibrationCoefficient = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_CalibrationCoefficient.setObjectName("txt_CalibrationCoefficient")
        self.gridLayout_6.addWidget(self.txt_CalibrationCoefficient, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_tcp_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tcp_settings.setObjectName("btn_tcp_settings")
        self.gridLayout_3.addWidget(self.btn_tcp_settings, 5, 1, 1, 1)
        self.txt_tcp_server_IP = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_tcp_server_IP.setObjectName("txt_tcp_server_IP")
        self.gridLayout_3.addWidget(self.txt_tcp_server_IP, 0, 1, 1, 1)
        self.label_tcp_server_IP = QtWidgets.QLabel(self.centralwidget)
        self.label_tcp_server_IP.setObjectName("label_tcp_server_IP")
        self.gridLayout_3.addWidget(self.label_tcp_server_IP, 0, 0, 1, 1)
        self.txt_timeout = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_timeout.setObjectName("txt_timeout")
        self.gridLayout_3.addWidget(self.txt_timeout, 3, 1, 1, 1)
        self.lbl_timeout = QtWidgets.QLabel(self.centralwidget)
        self.lbl_timeout.setObjectName("lbl_timeout")
        self.gridLayout_3.addWidget(self.lbl_timeout, 3, 0, 1, 1)
        self.txt_tcp_server_port = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_tcp_server_port.setObjectName("txt_tcp_server_port")
        self.gridLayout_3.addWidget(self.txt_tcp_server_port, 1, 1, 1, 1)
        self.label_tcp_server_port = QtWidgets.QLabel(self.centralwidget)
        self.label_tcp_server_port.setObjectName("label_tcp_server_port")
        self.gridLayout_3.addWidget(self.label_tcp_server_port, 1, 0, 1, 1)
        self.lbl_channel_num = QtWidgets.QLabel(self.centralwidget)
        self.lbl_channel_num.setEnabled(True)
        self.lbl_channel_num.setObjectName("lbl_channel_num")
        self.gridLayout_3.addWidget(self.lbl_channel_num, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_unlock.setText(_translate("MainWindow", "解鎖"))
        self.btn_lock.setText(_translate("MainWindow", "鎖定"))
        self.btn_ClearCurrentCount.setText(_translate("MainWindow", "清零當前壓合次數"))
        self.btn_SaveAlarmValue.setText(_translate("MainWindow", "保存"))
        self.lbl_Sensor_1SV_Lower.setText(_translate("MainWindow", "下限"))
        self.lbl_Sensor_3SV_Lower.setText(_translate("MainWindow", "下限"))
        self.lbl_Sensor_2SV.setText(_translate("MainWindow", "2SV"))
        self.lbl_Sensor_3SV.setText(_translate("MainWindow", "3SV"))
        self.lbl_Sensor_4SV.setText(_translate("MainWindow", "4SV"))
        self.lbl_Sensor_1SV_Upper.setText(_translate("MainWindow", "上限"))
        self.lbl_Sensor_3SV_Upper.setText(_translate("MainWindow", "上限"))
        self.lbl_Sensor_1SV.setText(_translate("MainWindow", "1SV"))
        self.lbl_Sensor_4SV_Lower.setText(_translate("MainWindow", "下限"))
        self.lbl_Sensor_2SV_Upper.setText(_translate("MainWindow", "上限"))
        self.lbl_Sensor_4SV_Upper.setText(_translate("MainWindow", "上限"))
        self.label.setText(_translate("MainWindow", "報警上下限"))
        self.lbl_Sensor_2SV_Lower.setText(_translate("MainWindow", "下限"))
        self.lbl_CalibrationCoefficient.setText(_translate("MainWindow", "當前校準係數"))
        self.btn_SaveCalibrationCoefficient.setText(_translate("MainWindow", "保存"))
        self.lbl_CurrentPressure.setText(_translate("MainWindow", "當前顯示值"))
        self.label_2.setText(_translate("MainWindow", "校準"))
        self.btn_tcp_settings.setText(_translate("MainWindow", "保存"))
        self.label_tcp_server_IP.setText(_translate("MainWindow", "服務器IP"))
        self.lbl_timeout.setText(_translate("MainWindow", "timout"))
        self.label_tcp_server_port.setText(_translate("MainWindow", "服務器Port"))
        self.lbl_channel_num.setText(_translate("MainWindow", "顯示通道數量"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "0"))
